// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/18 下午1:58:46
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Peggyy/Template_P/Vue-Template_P/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/plugins/**/*.{js,ts,mjs}","C:/Peggyy/Template_P/Vue-Template_P/composables/**/*.{js,ts,mjs}","C:/Peggyy/Template_P/Vue-Template_P/utils/**/*.{js,ts,mjs}","C:/Peggyy/Template_P/Vue-Template_P/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Peggyy/Template_P/Vue-Template_P/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;